CREATE TYPE "public"."forecast_gate_profile" AS ENUM('gate_early', 'gate_late');--> statement-breakpoint
CREATE TYPE "public"."forecast_origin_kind" AS ENUM('served', 'backfilled_holdout');--> statement-breakpoint
CREATE TABLE "curtailment_forecast_day" (
	"subsystem" "subsystem_code" NOT NULL,
	"target_date" date NOT NULL,
	"origin_kind" "forecast_origin_kind" NOT NULL,
	"gate_profile" "forecast_gate_profile" NOT NULL,
	"forecast_producer" "forecast_producer" NOT NULL,
	"run_label" text NOT NULL,
	"feature_set" text NOT NULL,
	"correction_regime" text NOT NULL,
	"threshold_mw" double precision NOT NULL,
	"day_total_p10_mwh" double precision NOT NULL,
	"day_total_p50_mwh" double precision NOT NULL,
	"day_total_p90_mwh" double precision NOT NULL,
	"peak_power_p10_mw" double precision NOT NULL,
	"peak_power_p50_mw" double precision NOT NULL,
	"peak_power_p90_mw" double precision NOT NULL,
	"day_occurrence_probability" double precision NOT NULL,
	"expected_mwh" double precision NOT NULL,
	"expected_wind_mwh" double precision NOT NULL,
	"expected_solar_mwh" double precision NOT NULL,
	"hours_p50_nonzero" integer NOT NULL,
	"derivation" text NOT NULL,
	"ensemble_draws" integer NOT NULL,
	"ensemble_seed" integer NOT NULL,
	"ensemble_calibration_days" integer NOT NULL,
	"trained_through" date NOT NULL,
	"risk_bin_elevated_from" double precision NOT NULL,
	"risk_bin_high_from" double precision NOT NULL,
	"data_version" integer NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"ingested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"value_digest" text NOT NULL,
	CONSTRAINT "curtailment_forecast_day_subsystem_target_date_origin_kind_gate_profile_data_version_pk" PRIMARY KEY("subsystem","target_date","origin_kind","gate_profile","data_version"),
	CONSTRAINT "curtailment_forecast_day_is_a_forecast" CHECK ("curtailment_forecast_day"."published_at" < ("curtailment_forecast_day"."target_date"::timestamp at time zone 'America/Sao_Paulo')),
	CONSTRAINT "curtailment_forecast_day_total_monotone" CHECK ("curtailment_forecast_day"."day_total_p10_mwh" <= "curtailment_forecast_day"."day_total_p50_mwh" and "curtailment_forecast_day"."day_total_p50_mwh" <= "curtailment_forecast_day"."day_total_p90_mwh"),
	CONSTRAINT "curtailment_forecast_day_peak_monotone" CHECK ("curtailment_forecast_day"."peak_power_p10_mw" <= "curtailment_forecast_day"."peak_power_p50_mw" and "curtailment_forecast_day"."peak_power_p50_mw" <= "curtailment_forecast_day"."peak_power_p90_mw"),
	CONSTRAINT "curtailment_forecast_day_probability" CHECK ("curtailment_forecast_day"."day_occurrence_probability" between 0 and 1),
	CONSTRAINT "curtailment_forecast_day_from_the_ensemble" CHECK ("curtailment_forecast_day"."derivation" = 'path_ensemble'),
	CONSTRAINT "curtailment_forecast_day_drew_something" CHECK ("curtailment_forecast_day"."ensemble_draws" > 0),
	CONSTRAINT "curtailment_forecast_day_hours_counted" CHECK ("curtailment_forecast_day"."hours_p50_nonzero" between 0 and 24),
	CONSTRAINT "curtailment_forecast_day_risk_edges_ordered" CHECK (0 < "curtailment_forecast_day"."risk_bin_elevated_from" and "curtailment_forecast_day"."risk_bin_elevated_from" < "curtailment_forecast_day"."risk_bin_high_from" and "curtailment_forecast_day"."risk_bin_high_from" < 1)
);
--> statement-breakpoint
CREATE TABLE "curtailment_forecast_hour" (
	"subsystem" "subsystem_code" NOT NULL,
	"valid_time" timestamp with time zone NOT NULL,
	"origin_kind" "forecast_origin_kind" NOT NULL,
	"gate_profile" "forecast_gate_profile" NOT NULL,
	"target_date" date NOT NULL,
	"local_hour" integer NOT NULL,
	"forecast_producer" "forecast_producer" NOT NULL,
	"run_label" text NOT NULL,
	"feature_set" text NOT NULL,
	"correction_regime" text NOT NULL,
	"threshold_mw" double precision NOT NULL,
	"occurrence_probability" double precision NOT NULL,
	"p10_mwh" double precision NOT NULL,
	"p50_mwh" double precision NOT NULL,
	"p90_mwh" double precision NOT NULL,
	"expected_mwh" double precision NOT NULL,
	"p50_wind_mwh" double precision NOT NULL,
	"p50_solar_mwh" double precision NOT NULL,
	"expected_wind_mwh" double precision NOT NULL,
	"expected_solar_mwh" double precision NOT NULL,
	"crossed" boolean NOT NULL,
	"data_version" integer NOT NULL,
	"published_at" timestamp with time zone NOT NULL,
	"ingested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"value_digest" text NOT NULL,
	CONSTRAINT "curtailment_forecast_hour_subsystem_valid_time_origin_kind_gate_profile_data_version_pk" PRIMARY KEY("subsystem","valid_time","origin_kind","gate_profile","data_version"),
	CONSTRAINT "curtailment_forecast_hour_is_a_forecast" CHECK ("curtailment_forecast_hour"."published_at" < "curtailment_forecast_hour"."valid_time"),
	CONSTRAINT "curtailment_forecast_hour_band_monotone" CHECK ("curtailment_forecast_hour"."p10_mwh" <= "curtailment_forecast_hour"."p50_mwh" and "curtailment_forecast_hour"."p50_mwh" <= "curtailment_forecast_hour"."p90_mwh"),
	CONSTRAINT "curtailment_forecast_hour_probability" CHECK ("curtailment_forecast_hour"."occurrence_probability" between 0 and 1),
	CONSTRAINT "curtailment_forecast_hour_local_hour" CHECK ("curtailment_forecast_hour"."local_hour" between 0 and 23),
	CONSTRAINT "curtailment_forecast_hour_threshold_positive" CHECK ("curtailment_forecast_hour"."threshold_mw" > 0)
);
--> statement-breakpoint
CREATE INDEX "curtailment_forecast_day_as_of" ON "curtailment_forecast_day" USING btree ("target_date","subsystem","ingested_at");--> statement-breakpoint
CREATE INDEX "curtailment_forecast_hour_as_of" ON "curtailment_forecast_hour" USING btree ("valid_time","subsystem","ingested_at");--> statement-breakpoint
CREATE INDEX "curtailment_forecast_hour_day" ON "curtailment_forecast_hour" USING btree ("target_date","subsystem","gate_profile","origin_kind");--> statement-breakpoint
CREATE VIEW "public"."canonical_forecast_day" AS (
  select distinct on (subsystem, target_date, origin_kind, gate_profile)
    subsystem,
    target_date,
    origin_kind,
    gate_profile,
    forecast_producer,
    run_label,
    feature_set,
    correction_regime,
    threshold_mw,
    day_total_p10_mwh,
    day_total_p50_mwh,
    day_total_p90_mwh,
    peak_power_p10_mw,
    peak_power_p50_mw,
    peak_power_p90_mw,
    day_occurrence_probability,
    expected_mwh,
    expected_wind_mwh,
    expected_solar_mwh,
    hours_p50_nonzero,
    derivation,
    ensemble_draws,
    ensemble_seed,
    ensemble_calibration_days,
    trained_through,
    risk_bin_elevated_from,
    risk_bin_high_from,
    data_version,
    published_at,
    ingested_at
  from curtailment_forecast_day
  where ingested_at <= canonical_as_of()
  order by subsystem, target_date, origin_kind, gate_profile,
           ingested_at desc, data_version desc
);--> statement-breakpoint
CREATE VIEW "public"."canonical_forecast_hour" AS (
  select distinct on (subsystem, valid_time, origin_kind, gate_profile)
    subsystem,
    valid_time,
    origin_kind,
    gate_profile,
    target_date,
    local_hour,
    forecast_producer,
    run_label,
    feature_set,
    correction_regime,
    threshold_mw,
    occurrence_probability,
    p10_mwh,
    p50_mwh,
    p90_mwh,
    expected_mwh,
    p50_wind_mwh,
    p50_solar_mwh,
    expected_wind_mwh,
    expected_solar_mwh,
    crossed,
    data_version,
    published_at,
    ingested_at
  from curtailment_forecast_hour
  where ingested_at <= canonical_as_of()
  order by subsystem, valid_time, origin_kind, gate_profile,
           ingested_at desc, data_version desc
);