"""Training — the hurdle's eight estimators, the bundle they live in, and the card.

`docs/specs/forecaster.md`, "The hurdle, composed", is the spec. What this
package owns is everything between a feature row and an artifact on the volume:

- :mod:`~wattsteer_ml.training.hyperparameters` — the published configuration,
  addressed by ``model_config_version`` and never searched.
- :mod:`~wattsteer_ml.training.contract` — the ordered feature names and the
  ``feature_rows`` definition, hashed together into ``feature_hash``.
- :mod:`~wattsteer_ml.training.design` — rows to a matrix, with nothing imputed.
- :mod:`~wattsteer_ml.training.calibration` — the isotonic map fitted on the
  calibration window, the reliability curve measured on pooled out-of-fold
  predictions, and the risk-class edges derived from it.
- :mod:`~wattsteer_ml.training.conformal` — the two one-sided conformal
  corrections fitted on the same window, the coverage they are checked by, and
  the drift hook that reports rather than adapts.
- :mod:`~wattsteer_ml.training.ensemble` — the randomised PIT matrix fitted on
  the same window, and the 500 whole-day draws every figure above hour grain is
  a quantile of.
- :mod:`~wattsteer_ml.training.national` — the national day: the four
  subsystems' paths added draw by draw under the ensemble's shared row index,
  and quantiles read off that. No copula, and no sum of quantiles anywhere.
- :mod:`~wattsteer_ml.training.background` — ``B(s, h)``, the matched sample
  the attribution's "typical" is averaged over, drawn once from the base-fit
  block and frozen into the bundle. It lives here rather than in
  :mod:`wattsteer_ml.diagnosis` because it is a part of the artifact; diagnosis
  re-exports it and reads it, and nothing here reads diagnosis.
- :mod:`~wattsteer_ml.training.bundle` — the frozen bundle, the card, and a load
  that refuses a partial mixture.
- :mod:`~wattsteer_ml.training.hurdle` — the fit, and the composition, which is
  :func:`wattsteer_ml.mixture.compose` and nothing else.

What it deliberately does **not** own: the mixture arithmetic (ticket 01), the
fold calendar (ticket 03), and the lane layout and promotion log (ticket 02).
Each of those is imported here and none is restated.
"""

from wattsteer_ml.training.background import (
    ARTIFACT_SOURCE,
    BACKGROUND_ROWS_PER_CELL,
    BACKGROUND_SEED,
    BASE_FIT_SOURCE,
    BackgroundCell,
    BackgroundError,
    CellKey,
    MatchedBackground,
    MissingBackgroundCellError,
    draw_artifact_background,
    draw_matched_background,
)
from wattsteer_ml.training.bundle import (
    BUNDLE_COMPRESSION,
    CONTRACT_FAULT_KEY,
    ESTIMATOR_FIELDS,
    GATE_BLOCK_KEY,
    BundleError,
    ContractMismatchError,
    HurdleBundle,
    LoadedArtifact,
    ModelCard,
    PartialBundleError,
    SubThresholdMeans,
    TrainingCounts,
    contract_fault,
    environment_versions,
    load_artifact,
    new_artifact_id,
    read_card,
    save_artifact,
    write_card,
)
from wattsteer_ml.training.calibration import (
    MAX_RISK_BIN_GAP,
    MIN_BIN_HOURS,
    MINIMUM_SUBSYSTEM_CALIBRATION_POSITIVE_ROWS,
    MINIMUM_SUBSYSTEM_CALIBRATION_ROWS,
    RELIABILITY_BINS,
    RISK_CLASSES,
    RISK_EDGE_STEP,
    BinMerge,
    Calibration,
    CalibrationError,
    IsotonicCalibrator,
    OutOfFoldPool,
    OutOfFoldPrediction,
    ReliabilityBin,
    ReliabilityCurve,
    RiskBinCheck,
    RiskBinDecision,
    RiskBins,
    RiskBinsUndeterminedError,
    RiskClass,
    SubsystemCalibration,
    SubsystemIsotonic,
    calibrate,
    calibrate_by_subsystem,
    derive_risk_bins,
    outside_calibration_window,
    wilson_half_width,
)
from wattsteer_ml.training.conformal import (
    CORRECTION_REGIME,
    COVERAGE_GUARDRAIL,
    LOWER_TAIL_NOT_FITTED,
    NOMINAL_MISCOVERAGE,
    TARGET_COVERAGE,
    ConformalCorrection,
    ConformalError,
    CoverageCell,
    CoverageReport,
    DeltaDrift,
    ScoredHour,
    SubsystemCorrections,
    SubsystemDeltaLo,
    conformal_rank,
    conformalise,
    conformalise_by_subsystem,
    lower_correction_fraction,
    minimum_calibration_rows,
    residuals,
    upper_correction_fraction,
)
from wattsteer_ml.training.contract import (
    FUNCTION_DEFINITION_SQL,
    LABEL_PREFIX,
    STAMP_COLUMNS,
    Dtype,
    FeatureColumn,
    FeatureContract,
    FeatureContractError,
    feature_column_names,
    read_feature_function_definition,
)
from wattsteer_ml.training.design import (
    DesignError,
    FeatureBlock,
    RowStamp,
)
from wattsteer_ml.training.ensemble import (
    ENSEMBLE_DRAWS,
    ENSEMBLE_SEED,
    KS_CRITICAL_95,
    KS_FAMILYWISE_LEVEL,
    MIN_ENSEMBLE_DAYS,
    PIT_COLUMN_KEYS,
    PIT_COLUMNS,
    DayGrainCoverage,
    DayGrainForecast,
    DrawPlan,
    EnsembleError,
    PathEnsemble,
    PitMatrix,
    draw_day_grain,
    ensemble_quantile,
    fit_pit_matrix,
    ks_critical,
    ks_uniform_statistic,
    ks_uniform_tolerance,
    pit_column,
    randomised_pit,
)
from wattsteer_ml.training.headline_check import (
    HEADLINE_CHECK_SEED,
    HEADLINE_CHECK_TARGETS,
    HEADLINE_VERDICTS,
    GroupHeadlineCheck,
    HeadlineCheckError,
    HeadlineFeatureCheck,
    HeadlineVerdict,
    check_headline_features,
)
from wattsteer_ml.training.hurdle import (
    HourEstimates,
    HourForecast,
    TrainedFold,
    TrainingError,
    compose_estimates,
    day_grain_rows,
    expected_mwh_for_block,
    fit_sub_threshold_means,
    forecast_rows,
    out_of_fold_occurrence,
    partition_rows,
    train_fold,
)
from wattsteer_ml.training.hyperparameters import (
    ESTIMATOR_FAMILY,
    MODEL_CONFIG_V1,
    MODEL_CONFIG_V2,
    MODEL_CONFIG_VERSION,
    MODEL_CONFIGS,
    ModelConfig,
    UnknownModelConfigError,
    model_config,
)
from wattsteer_ml.training.national import (
    NATIONAL_DERIVATION,
    NATIONAL_PRODUCER,
    ForecastOrigin,
    NationalDayGrain,
    NationalError,
    national_day_grain,
    national_rows,
    subsystem_day_expectations,
)

__all__ = [
    "ARTIFACT_SOURCE",
    "BACKGROUND_ROWS_PER_CELL",
    "BACKGROUND_SEED",
    "BASE_FIT_SOURCE",
    "BUNDLE_COMPRESSION",
    "CONTRACT_FAULT_KEY",
    "CORRECTION_REGIME",
    "COVERAGE_GUARDRAIL",
    "ENSEMBLE_DRAWS",
    "ENSEMBLE_SEED",
    "ESTIMATOR_FAMILY",
    "ESTIMATOR_FIELDS",
    "FUNCTION_DEFINITION_SQL",
    "GATE_BLOCK_KEY",
    "HEADLINE_CHECK_SEED",
    "HEADLINE_CHECK_TARGETS",
    "HEADLINE_VERDICTS",
    "KS_CRITICAL_95",
    "KS_FAMILYWISE_LEVEL",
    "LABEL_PREFIX",
    "LOWER_TAIL_NOT_FITTED",
    "MAX_RISK_BIN_GAP",
    "MINIMUM_SUBSYSTEM_CALIBRATION_POSITIVE_ROWS",
    "MINIMUM_SUBSYSTEM_CALIBRATION_ROWS",
    "MIN_BIN_HOURS",
    "MIN_ENSEMBLE_DAYS",
    "MODEL_CONFIGS",
    "MODEL_CONFIG_V1",
    "MODEL_CONFIG_V2",
    "MODEL_CONFIG_VERSION",
    "NATIONAL_DERIVATION",
    "NATIONAL_PRODUCER",
    "NOMINAL_MISCOVERAGE",
    "PIT_COLUMNS",
    "PIT_COLUMN_KEYS",
    "RELIABILITY_BINS",
    "RISK_CLASSES",
    "RISK_EDGE_STEP",
    "STAMP_COLUMNS",
    "TARGET_COVERAGE",
    "BackgroundCell",
    "BackgroundError",
    "BinMerge",
    "BundleError",
    "Calibration",
    "CalibrationError",
    "CellKey",
    "ConformalCorrection",
    "ConformalError",
    "ContractMismatchError",
    "CoverageCell",
    "CoverageReport",
    "DayGrainCoverage",
    "DayGrainForecast",
    "DeltaDrift",
    "DesignError",
    "DrawPlan",
    "Dtype",
    "EnsembleError",
    "FeatureBlock",
    "FeatureColumn",
    "FeatureContract",
    "FeatureContractError",
    "ForecastOrigin",
    "GroupHeadlineCheck",
    "HeadlineCheckError",
    "HeadlineFeatureCheck",
    "HeadlineVerdict",
    "HourEstimates",
    "HourForecast",
    "HurdleBundle",
    "IsotonicCalibrator",
    "LoadedArtifact",
    "MatchedBackground",
    "MissingBackgroundCellError",
    "ModelCard",
    "ModelConfig",
    "NationalDayGrain",
    "NationalError",
    "OutOfFoldPool",
    "OutOfFoldPrediction",
    "PartialBundleError",
    "PathEnsemble",
    "PitMatrix",
    "ReliabilityBin",
    "ReliabilityCurve",
    "RiskBinCheck",
    "RiskBinDecision",
    "RiskBins",
    "RiskBinsUndeterminedError",
    "RiskClass",
    "RowStamp",
    "ScoredHour",
    "SubThresholdMeans",
    "SubsystemCalibration",
    "SubsystemCorrections",
    "SubsystemDeltaLo",
    "SubsystemIsotonic",
    "TrainedFold",
    "TrainingCounts",
    "TrainingError",
    "UnknownModelConfigError",
    "calibrate",
    "calibrate_by_subsystem",
    "check_headline_features",
    "compose_estimates",
    "conformal_rank",
    "conformalise",
    "conformalise_by_subsystem",
    "contract_fault",
    "day_grain_rows",
    "derive_risk_bins",
    "draw_artifact_background",
    "draw_day_grain",
    "draw_matched_background",
    "ensemble_quantile",
    "environment_versions",
    "expected_mwh_for_block",
    "feature_column_names",
    "fit_pit_matrix",
    "fit_sub_threshold_means",
    "forecast_rows",
    "ks_critical",
    "ks_uniform_statistic",
    "ks_uniform_tolerance",
    "load_artifact",
    "lower_correction_fraction",
    "minimum_calibration_rows",
    "model_config",
    "national_day_grain",
    "national_rows",
    "new_artifact_id",
    "out_of_fold_occurrence",
    "outside_calibration_window",
    "partition_rows",
    "pit_column",
    "randomised_pit",
    "read_card",
    "read_feature_function_definition",
    "residuals",
    "save_artifact",
    "subsystem_day_expectations",
    "train_fold",
    "upper_correction_fraction",
    "wilson_half_width",
    "write_card",
]
