"""Training — the hurdle's six estimators, the bundle they live in, and the card.

`docs/specs/forecaster.md`, "The hurdle, composed", is the spec. What this
package owns is everything between a feature row and an artifact on the volume:

- :mod:`~wattsteer_ml.training.hyperparameters` — the published configuration,
  addressed by ``model_config_version`` and never searched.
- :mod:`~wattsteer_ml.training.contract` — the ordered feature names and the
  ``feature_rows`` definition, hashed together into ``feature_hash``.
- :mod:`~wattsteer_ml.training.design` — rows to a matrix, with nothing imputed.
- :mod:`~wattsteer_ml.training.calibration` — the isotonic map fitted on the
  calibration window, the reliability curve measured on pooled out-of-fold
  predictions, and the risk-class edges derived from it.
- :mod:`~wattsteer_ml.training.conformal` — the two one-sided conformal
  corrections fitted on the same window, the coverage they are checked by, and
  the drift hook that reports rather than adapts.
- :mod:`~wattsteer_ml.training.ensemble` — the randomised PIT matrix fitted on
  the same window, and the 500 whole-day draws every figure above hour grain is
  a quantile of.
- :mod:`~wattsteer_ml.training.bundle` — the frozen bundle, the card, and a load
  that refuses a partial mixture.
- :mod:`~wattsteer_ml.training.hurdle` — the fit, and the composition, which is
  :func:`wattsteer_ml.mixture.compose` and nothing else.

What it deliberately does **not** own: the mixture arithmetic (ticket 01), the
fold calendar (ticket 03), and the lane layout and promotion log (ticket 02).
Each of those is imported here and none is restated.
"""

from wattsteer_ml.training.bundle import (
    ESTIMATOR_FIELDS,
    BundleError,
    ContractMismatchError,
    HurdleBundle,
    LoadedArtifact,
    ModelCard,
    PartialBundleError,
    SubThresholdMeans,
    TrainingCounts,
    environment_versions,
    load_artifact,
    new_artifact_id,
    save_artifact,
)
from wattsteer_ml.training.calibration import (
    MAX_RISK_BIN_GAP,
    MIN_BIN_HOURS,
    RELIABILITY_BINS,
    RISK_CLASSES,
    RISK_EDGE_STEP,
    BinMerge,
    Calibration,
    CalibrationError,
    IsotonicCalibrator,
    OutOfFoldPool,
    OutOfFoldPrediction,
    ReliabilityBin,
    ReliabilityCurve,
    RiskBinCheck,
    RiskBinDecision,
    RiskBins,
    RiskBinsUndeterminedError,
    RiskClass,
    calibrate,
    derive_risk_bins,
    outside_calibration_window,
    wilson_half_width,
)
from wattsteer_ml.training.conformal import (
    COVERAGE_GUARDRAIL,
    NOMINAL_MISCOVERAGE,
    TARGET_COVERAGE,
    ConformalCorrection,
    ConformalError,
    CoverageCell,
    CoverageReport,
    DeltaDrift,
    ScoredHour,
    conformal_rank,
    conformalise,
    minimum_calibration_rows,
    residuals,
    upper_correction_fraction,
)
from wattsteer_ml.training.contract import (
    FUNCTION_DEFINITION_SQL,
    LABEL_PREFIX,
    STAMP_COLUMNS,
    Dtype,
    FeatureColumn,
    FeatureContract,
    FeatureContractError,
    feature_column_names,
    read_feature_function_definition,
)
from wattsteer_ml.training.design import (
    DesignError,
    FeatureBlock,
    RowStamp,
)
from wattsteer_ml.training.ensemble import (
    ENSEMBLE_DRAWS,
    ENSEMBLE_SEED,
    KS_CRITICAL_95,
    KS_FAMILYWISE_LEVEL,
    MIN_ENSEMBLE_DAYS,
    PIT_COLUMN_KEYS,
    PIT_COLUMNS,
    DayGrainCoverage,
    DayGrainForecast,
    DrawPlan,
    EnsembleError,
    PathEnsemble,
    PitMatrix,
    draw_day_grain,
    ensemble_quantile,
    fit_pit_matrix,
    ks_critical,
    ks_uniform_statistic,
    ks_uniform_tolerance,
    pit_column,
    randomised_pit,
)
from wattsteer_ml.training.hurdle import (
    HourEstimates,
    HourForecast,
    TrainedFold,
    TrainingError,
    compose_estimates,
    day_grain_rows,
    expected_mwh_for_block,
    fit_sub_threshold_means,
    forecast_rows,
    partition_rows,
    train_fold,
)
from wattsteer_ml.training.hyperparameters import (
    ESTIMATOR_FAMILY,
    MODEL_CONFIG_V1,
    MODEL_CONFIG_VERSION,
    MODEL_CONFIGS,
    ModelConfig,
    UnknownModelConfigError,
    model_config,
)

__all__ = [
    "COVERAGE_GUARDRAIL",
    "ENSEMBLE_DRAWS",
    "ENSEMBLE_SEED",
    "ESTIMATOR_FAMILY",
    "ESTIMATOR_FIELDS",
    "FUNCTION_DEFINITION_SQL",
    "KS_CRITICAL_95",
    "KS_FAMILYWISE_LEVEL",
    "LABEL_PREFIX",
    "MAX_RISK_BIN_GAP",
    "MIN_BIN_HOURS",
    "MIN_ENSEMBLE_DAYS",
    "MODEL_CONFIGS",
    "MODEL_CONFIG_V1",
    "MODEL_CONFIG_VERSION",
    "NOMINAL_MISCOVERAGE",
    "PIT_COLUMNS",
    "PIT_COLUMN_KEYS",
    "RELIABILITY_BINS",
    "RISK_CLASSES",
    "RISK_EDGE_STEP",
    "STAMP_COLUMNS",
    "TARGET_COVERAGE",
    "BinMerge",
    "BundleError",
    "Calibration",
    "CalibrationError",
    "ConformalCorrection",
    "ConformalError",
    "ContractMismatchError",
    "CoverageCell",
    "CoverageReport",
    "DayGrainCoverage",
    "DayGrainForecast",
    "DeltaDrift",
    "DesignError",
    "DrawPlan",
    "Dtype",
    "EnsembleError",
    "FeatureBlock",
    "FeatureColumn",
    "FeatureContract",
    "FeatureContractError",
    "HourEstimates",
    "HourForecast",
    "HurdleBundle",
    "IsotonicCalibrator",
    "LoadedArtifact",
    "ModelCard",
    "ModelConfig",
    "OutOfFoldPool",
    "OutOfFoldPrediction",
    "PartialBundleError",
    "PathEnsemble",
    "PitMatrix",
    "ReliabilityBin",
    "ReliabilityCurve",
    "RiskBinCheck",
    "RiskBinDecision",
    "RiskBins",
    "RiskBinsUndeterminedError",
    "RiskClass",
    "RowStamp",
    "ScoredHour",
    "SubThresholdMeans",
    "TrainedFold",
    "TrainingCounts",
    "TrainingError",
    "UnknownModelConfigError",
    "calibrate",
    "compose_estimates",
    "conformal_rank",
    "conformalise",
    "day_grain_rows",
    "derive_risk_bins",
    "draw_day_grain",
    "ensemble_quantile",
    "environment_versions",
    "expected_mwh_for_block",
    "feature_column_names",
    "fit_pit_matrix",
    "fit_sub_threshold_means",
    "forecast_rows",
    "ks_critical",
    "ks_uniform_statistic",
    "ks_uniform_tolerance",
    "load_artifact",
    "minimum_calibration_rows",
    "model_config",
    "new_artifact_id",
    "outside_calibration_window",
    "partition_rows",
    "pit_column",
    "randomised_pit",
    "read_feature_function_definition",
    "residuals",
    "save_artifact",
    "train_fold",
    "upper_correction_fraction",
    "wilson_half_width",
]
