import {
  DEFAULT_LOCALE,
  LOCALES,
  type Locale,
  type LocalizedPath,
  languageTag,
  localePath,
} from "@/i18n/locale";
import { SITE_URL } from "./config";

/**
 * The absolute URL of a page in a locale — the one form that `sitemap.xml`,
 * `<link rel="canonical">` and every `hreflang` alternate must agree on.
 * Disagreement between a page's canonical and the sitemap's idea of it is the
 * usual reason hreflang gets silently ignored.
 */
export function pageUrl(locale: Locale, path: LocalizedPath = ""): string {
  return `${SITE_URL}${localePath(locale, path)}`;
}

export interface Alternate {
  hrefLang: string;
  href: string;
}

/**
 * The full alternate set for a page: one entry per locale plus `x-default`.
 *
 * `x-default` points at Portuguese. Brazil is the primary market, so a crawler
 * or user-agent that expresses no preference gets pt-BR rather than English —
 * the same rule the loading screen at `/` applies to a human visitor who has
 * never chosen.
 */
export function alternatesFor(path: LocalizedPath = ""): Alternate[] {
  const entries: Alternate[] = LOCALES.map((locale) => ({
    hrefLang: languageTag(locale),
    href: pageUrl(locale, path),
  }));
  entries.push({ hrefLang: "x-default", href: pageUrl(DEFAULT_LOCALE, path) });
  return entries;
}

// `GATE_URL` used to be exported here — the bare `/` URL, for a page that is
// `noindex` and therefore never gets a canonical. Nothing ever imported it,
// and the page it named is now the loading screen, so it is gone rather than
// renamed: a constant with no reader is a claim nothing checks.

/**
 * The share card.
 *
 * `public/og.png` is 1200×630 — the size Facebook, LinkedIn, Slack and X all
 * document, and the one that survives every crawler's own re-crop. It is
 * generated by `scripts/generate-assets.ts` from the same mark geometry as the
 * favicons, so it cannot drift from the brand.
 *
 * The dimensions are declared alongside the URL because a crawler that has to
 * fetch the image to learn them will often show nothing on the first share —
 * `og:image:width`/`height` are what let it lay the card out before the bytes
 * arrive. They are asserted against the file in `test/seo.test.ts` rather than
 * trusted, since a regenerated asset at another size would otherwise make the
 * tags quietly wrong.
 */
export const OG_IMAGE_PATH = "/og.png";
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;

/** The absolute share-card URL. Crawlers reject a relative `og:image`. */
export const OG_IMAGE_URL = `${SITE_URL}${OG_IMAGE_PATH}`;

/**
 * The site's identity, as one `@graph` rather than three loose objects.
 *
 * A graph with `@id`s lets `WebSite.publisher` and `SoftwareApplication.author`
 * "point at" the Organization instead of restating it, which is what keeps
 * Google from reading three unrelated entities off one page. The `@id`s are
 * URL fragments on the site origin because that is the convention schema.org
 * consumers expect for a node that is not itself a fetchable page.
 *
 * `SoftwareApplication` rather than `Product`: WattSteer is software with a
 * browser as its runtime, it has no SKU, and `Product` without `offers` or
 * `aggregateRating` is a shape Google's rich-results test rejects. The price
 * is declared as 0 because the site is public and read-only — an omitted
 * `offers` would leave "is this free?" unanswered, and inventing a price would
 * be a lie in structured data, which is the worst place to put one.
 *
 * Per-locale: `inLanguage` and the description follow the page they sit on, so
 * `/pt/` and `/en/` describe the same entity in the reader's language rather
 * than duplicating one language across both.
 */
export function siteGraph(locale: Locale, description: string): object {
  const organizationId = `${SITE_URL}/#organization`;
  const websiteId = `${SITE_URL}/#website`;
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": organizationId,
        name: "WattSteer",
        url: SITE_URL,
        logo: {
          "@type": "ImageObject",
          url: `${SITE_URL}/icon-512.png`,
          width: 512,
          height: 512,
        },
        // The locale roots, not the bare origin: `/` is a loading screen that
        // redirects, and pointing `sameAs` at it would name a page with no
        // content as an alternative identity for the organisation.
        sameAs: LOCALES.map((option) => pageUrl(option)),
      },
      {
        "@type": "WebSite",
        "@id": websiteId,
        name: "WattSteer",
        url: pageUrl(locale),
        description,
        inLanguage: languageTag(locale),
        publisher: { "@id": organizationId },
      },
      {
        "@type": "SoftwareApplication",
        "@id": `${SITE_URL}/#application`,
        name: "WattSteer",
        url: `${SITE_URL}/app`,
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web",
        description,
        inLanguage: languageTag(locale),
        image: OG_IMAGE_URL,
        author: { "@id": organizationId },
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "BRL",
        },
      },
    ],
  };
}
